---
# Deploy Traefik

- name: Install Docker
  ansible.builtin.import_role:
    name: deadnews.util.docker
  vars:
    docker_rootless: false
    docker_config_daemon: files/daemon.json

- name: Setup Traefik
  block:
    - name: Create a network for Traefik
      community.docker.docker_network:
        name: traefik

    - name: Deploy Traefik
      ansible.builtin.import_role:
        name: deadnews.util.docker_compose
      vars:
        docker_compose_project: traefik
        docker_compose_target_dir: ~/docker-compose
        docker_compose_files:
          - src: files/docker-compose.yml
          - src: templates/vector.yml.j2

- name: Verify that Whoami is responding
  ansible.builtin.uri:
    url: http://127.0.0.1:80
    headers:
      Host: whoami.localhost
  register: traefik_verify
  retries: 12
  delay: 5
  until: traefik_verify is not failed
